### ISSUE TITLE
Train/drop track length incorrectly calculated for backwards-facing trains (also momentum thing)

### ISSUE THREAD

**Issue by coastercrab** [oli414/AdvancedTrack#13]
On a shuttle-operating transport ride with 2 lift/drop tracks - one for each direction - a train facing backwards will move only the first piece of drop track. The entire train does move, but only the first car is released when the track finishes moving, as the rest of the track did not.

(Also, powered vehicles appear to retain their previous pre-braking momentum once released from a lift/drop track)

https://user-images.githubusercontent.com/105173907/167314588-15684b1d-1b44-4af6-ab05-c4184b2c9437.mp4

**Comment by oli414** [comment]
Nice find, I didn't intend for this to work for vehicles that go backward, but it looks like it works quite a bit already so why not.

I'm working on a fix now

**Comment by oli414** [comment]
This has been fixed in the latest release:
https://github.com/oli414/AdvancedTrack/releases

**Comment by coastercrab** [comment]
Works wonderfully now! Lovely to see in motion, thanks for all you've done!
