### ISSUE TITLE
Trigger switch depending on vehicle/train direction?

### ISSUE THREAD

**Issue by ExileFox** [oli414/AdvancedTrack#5]
![image](https://user-images.githubusercontent.com/2000703/98975506-7bb68700-2516-11eb-8952-36a8f4d8f18c.png)

I want the train to go up the hill, roll back and up the other hill, then run the circuit.

Is this possible ?
If not, could this be added?

**Comment by oli414** [comment]
Added :-) It'll be available with the next release
